### ISSUE TITLE
copyObject

### ISSUE THREAD

**Issue by j-oi** [bradenmacdonald/s3-lite-client#23]
Thank you for adding the copyObject, could it please have the ability to add the metadata options?

**Comment by bradenmacdonald** [comment]
What's your use case? Can you tell me how to test it? Would that require setting `x-amz-metadata-directive: REPLACE` ?

**Comment by j-oi** [comment]
I am using for handling text and images.
when putting object at the beginning 
client.putObject(file.path,file.data,{bucketName:'aws',metadata:{"Cache-Control": "public, max-age=31536000","x-amz-acl":"public-read","Content-Type":file.type}});

Then if want to duplicate use copy object, use client.copyObject({sourceBucketName:'aws',sourceKey:path},newfilename,{bucketName:'aws'});

However, it does not copy the original metadata or option to set a new metadata.  

I'm not aware that it accepts metadata argument when looking at client.ts

public async copyObject(
    source: { sourceBucketName?: string; sourceKey: string; sourceVersionId?: string },
    objectName: string,
    options?: { bucketName?: string },
  )

**Comment by bradenmacdonald** [comment]
@j-oi This feature is now available in version 0.7.4.

https://jsr.io/@bradenmacdonald/s3-lite-client
