### ISSUE TITLE
Can this lib be published to npm as well ?

### ISSUE THREAD

**Issue by riderx** [bradenmacdonald/s3-lite-client#26]
I use this lib in deno function and wanted to use the same in node code and it's not available, but if i just copy the code it work so i suppose you could publish it as well

**Comment by bradenmacdonald** [comment]
How does it work if you "just copy the code"? Node doesn't support TypeScript, so it's necessary to use a tool like [dnt](https://github.com/denoland/dnt) before Node can run it, unless you already have TypeScript/webpack/etc set up in your project.

I _could_ set up dnt and publish to npm, but I don't have a strong motivation to do this. The [minio client](https://www.npmjs.com/package/minio) is already available on NPM and is what this one is based on, so it has similar features.

**Comment by bradenmacdonald** [comment]
Closing this for now. I'm not going to publish on npm but it can be used with npm (and many others) via JSR: https://jsr.io/@bradenmacdonald/s3-lite-client#installation

**Comment by riderx** [comment]
Thanks @bradenmacdonald i'm using it but the typescript is missing i'm not sure it's from you i found this :
https://github.com/jsr-io/jsr/issues/216

**Comment by bradenmacdonald** [comment]
@riderx  The types are working just fine for me. Try this:

```sh
mkdir test-project
cd test-project
echo '{"type": "module"}' > package.json
npm install --save typescript
npx jsr add @bradenmacdonald/s3-lite-client
echo 'import { S3Client } from "@bradenmacdonald/s3-lite-client";' > test.ts
echo '{"compilerOptions": {"module": "ESNext", "moduleResolution": "Bundler", "lib": ["ESNext", "DOM"], "strict": true}}' > tsconfig.json
npx tsc
```

No output means the type checking worked.

Here you can see the types showing up in VS Code in that same NodeJS project:
![Screenshot](https://github.com/user-attachments/assets/5e0ff27b-5807-411a-93c4-c9ad0781caac)

**Comment by riderx** [comment]
"module": "ESNext", "moduleResolution": "Bundler" did the trick !
