### ISSUE TITLE
Feature request: Compute S3 Compatible Bucket/Folder Size Without Stat Request for All Objects

### ISSUE THREAD

**Issue by nestarz** [bradenmacdonald/s3-lite-client#36]
Proposal: A feature that enables the computation of the size of an S3 compatible bucket or folder without requiring a stat request for all objects individually. Implementing this feature would significantly improve efficiency and reduce overhead when managing large-scale storage environments.

**Comment by bradenmacdonald** [comment]
Is that even possible? I'm not aware of an API for that, other than iterating over the objects via stat.

**Comment by nestarz** [comment]
You are right, it's not. The most we can do is to provide an utility tool around stat to support this, but that may be out of scope of this package. Sorry.
