### ISSUE TITLE
Cant load this lib on deno env (supabase)

### ISSUE THREAD

**Issue by ororsatti** [bradenmacdonald/s3-lite-client#41]
im constantly seeing this error: 
![Screenshot 2024-08-05 at 12 23 20](https://github.com/user-attachments/assets/ce9b3708-747a-4ab1-b900-7fcb7e638e0d)

i have updated to latest deno, cached the std/io and std/assert libs, and yet, this error persists.

**Comment by bradenmacdonald** [comment]
It could be some error specific to the supabase environment. It seems like it's not resolving the JSR version of `@std/io` properly. The version specified is `^0.224` which is supposed to resolve to [`0.224.4`](https://jsr.io/@std/io/versions) (or similar). There is no version `0.224` or `^0.224` so if it takes the version literally instead of parsing it as a semver constraint, that would explain the error you're seeing.

Can you try running these commands in the deno repl, from a shell? I tried just now and it worked fine.

```
% deno
Deno 1.45.5

> import { S3Client } from "jsr:@bradenmacdonald/s3-lite-client@0.7.6";

> const s3client = new S3Client({
  endPoint: "s3.us-east-1.amazonaws.com",
  port: 443,
  useSSL: true,
  region: "us-east-1",
  bucket: "openalex",
  pathStyle: false,
});

> for await (const obj of s3client.listObjects({ prefix: "data/concepts/" })) {
  console.log(obj);
}
```

**Comment by ororsatti** [comment]
> It could be some error specific to the supabase environment. It seems like it's not resolving the JSR version of `@std/io` properly. The version specified is `^0.224` which is supposed to resolve to [`0.224.4`](https://jsr.io/@std/io/versions) (or similar). There is no version `0.224` or `^0.224` so if it takes the version literally instead of parsing it as a semver constraint, that would explain the error you're seeing.
> 
> Can you try running these commands in the deno repl, from a shell? I tried just now and it worked fine.
> 
> ```
> % deno
> Deno 1.45.5
> 
> > import { S3Client } from "jsr:@bradenmacdonald/s3-lite-client@0.7.6";
> 
> > const s3client = new S3Client({
>   endPoint: "s3.us-east-1.amazonaws.com",
>   port: 443,
>   useSSL: true,
>   region: "us-east-1",
>   bucket: "openalex",
>   pathStyle: false,
> });
> 
> > for await (const obj of s3client.listObjects({ prefix: "data/concepts/" })) {
>   console.log(obj);
> }
> ```

it worked!

tho im not sure why in supabase it fails to install it every time.
should I specify it in deno.json or something?

**Comment by bradenmacdonald** [comment]
Sorry, I'm not sure why that might be. You'll have to debug it in the supabase environment. If need be, you can always just copy the code into your project (and edit the import of std/io/buffer or just copy that file in too). It is about 9 separate files, but they're each small.

**Comment by bradenmacdonald** [comment]
Closing as I believe this is an issue with Supabase env, JSR, and/or Deno - but not specific to s3-lite-client. Feel free to re-open if you think this is a legitimate bug with this library.
